# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portao.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='portao.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cportao.proto\"\x1e\n\x0cStatusPortao\x12\x0e\n\x06status\x18\x01 \x01(\x02\x32g\n\x06Portao\x12-\n\x0b\x61\x62rirPortao\x12\r.StatusPortao\x1a\r.StatusPortao\"\x00\x12.\n\x0c\x66\x65\x63harPortao\x12\r.StatusPortao\x1a\r.StatusPortao\"\x00\x62\x06proto3'
)




_STATUSPORTAO = _descriptor.Descriptor(
  name='StatusPortao',
  full_name='StatusPortao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='StatusPortao.status', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['StatusPortao'] = _STATUSPORTAO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusPortao = _reflection.GeneratedProtocolMessageType('StatusPortao', (_message.Message,), {
  'DESCRIPTOR' : _STATUSPORTAO,
  '__module__' : 'portao_pb2'
  # @@protoc_insertion_point(class_scope:StatusPortao)
  })
_sym_db.RegisterMessage(StatusPortao)



_PORTAO = _descriptor.ServiceDescriptor(
  name='Portao',
  full_name='Portao',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=48,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='abrirPortao',
    full_name='Portao.abrirPortao',
    index=0,
    containing_service=None,
    input_type=_STATUSPORTAO,
    output_type=_STATUSPORTAO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='fecharPortao',
    full_name='Portao.fecharPortao',
    index=1,
    containing_service=None,
    input_type=_STATUSPORTAO,
    output_type=_STATUSPORTAO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PORTAO)

DESCRIPTOR.services_by_name['Portao'] = _PORTAO

# @@protoc_insertion_point(module_scope)
